// Code generated by sqlc. DO NOT EDIT.
// source: channels.sql

package mdb

import (
	"context"
)

const createChannel = `-- name: CreateChannel :exec
INSERT INTO channels (channel_name, created_at, hiccup_count)
  VALUES ($1, NOW(), 0)
  ON CONFLICT DO NOTHING
`

func (q *Queries) CreateChannel(ctx context.Context, channelName string) error {
	_, err := q.db.ExecContext(ctx, createChannel, channelName)
	return err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels
  WHERE channel_name = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, channelName string) error {
	_, err := q.db.ExecContext(ctx, deleteChannel, channelName)
	return err
}

const getChannelNames = `-- name: GetChannelNames :many
SELECT channel_name FROM channels
`

func (q *Queries) GetChannelNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getChannelNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var channel_name string
		if err := rows.Scan(&channel_name); err != nil {
			return nil, err
		}
		items = append(items, channel_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHiccupCount = `-- name: GetHiccupCount :one
SELECT hiccup_count FROM channels
  WHERE channel_name = $1
`

func (q *Queries) GetHiccupCount(ctx context.Context, channelName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getHiccupCount, channelName)
	var hiccup_count int64
	err := row.Scan(&hiccup_count)
	return hiccup_count, err
}

const updateHiccupCount = `-- name: UpdateHiccupCount :exec
UPDATE channels
  SET hiccup_count = hiccup_count + $2
  WHERE channel_name = $1
`

type UpdateHiccupCountParams struct {
	ChannelName string
	HiccupCount int64
}

func (q *Queries) UpdateHiccupCount(ctx context.Context, arg UpdateHiccupCountParams) error {
	_, err := q.db.ExecContext(ctx, updateHiccupCount, arg.ChannelName, arg.HiccupCount)
	return err
}
