// Code generated by sqlc. DO NOT EDIT.

package mdb

import (
	"database/sql"
	"time"
)

type Channel struct {
	ChannelName string
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	HiccupCount int64
}

type Message struct {
	ID          int32
	ChannelName string
	Sender      string
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	Message     string
}

type User struct {
	ChannelName  string
	Sender       string
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
	WordCount    int64
	MessageCount int64
	WatchTime    int64
	Emoji        sql.NullString
	TextColor    sql.NullString
}
