// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Approval struct {
	ChannelID string
	UserID    string
}

type Channel struct {
	ChannelID string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type Command struct {
	ChannelID string
	Name      string
	Template  string
}

type Counter struct {
	ChannelID string
	Name      string
	Value     int64
}

type Message struct {
	ID        int32
	ChannelID string
	SenderID  string
	CreatedAt time.Time
	Message   string
}

type User struct {
	ChannelID    string
	SenderID     string
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
	WordCount    int64
	MessageCount int64
	WatchTime    int64
}
