// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Channels    string
	Messages    string
	UserMetrics string
	Users       string
}{
	Channels:    "channels",
	Messages:    "messages",
	UserMetrics: "user_metrics",
	Users:       "users",
}
