// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// UserMetric is an object representing the database table.
type UserMetric struct {
	Sender       string      `boil:"sender" json:"sender" toml:"sender" yaml:"sender"`
	ChannelName  string      `boil:"channel_name" json:"channel_name" toml:"channel_name" yaml:"channel_name"`
	WordCount    null.Int64  `boil:"word_count" json:"word_count,omitempty" toml:"word_count" yaml:"word_count,omitempty"`
	MessageCount null.Int64  `boil:"message_count" json:"message_count,omitempty" toml:"message_count" yaml:"message_count,omitempty"`
	WatchTime    null.Int64  `boil:"watch_time" json:"watch_time,omitempty" toml:"watch_time" yaml:"watch_time,omitempty"`
	CreatedAt    null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt    null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	Emoji        null.String `boil:"emoji" json:"emoji,omitempty" toml:"emoji" yaml:"emoji,omitempty"`
	TextColor    null.String `boil:"text_color" json:"text_color,omitempty" toml:"text_color" yaml:"text_color,omitempty"`

	R *userMetricR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userMetricL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserMetricColumns = struct {
	Sender       string
	ChannelName  string
	WordCount    string
	MessageCount string
	WatchTime    string
	CreatedAt    string
	UpdatedAt    string
	Emoji        string
	TextColor    string
}{
	Sender:       "sender",
	ChannelName:  "channel_name",
	WordCount:    "word_count",
	MessageCount: "message_count",
	WatchTime:    "watch_time",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	Emoji:        "emoji",
	TextColor:    "text_color",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}

var UserMetricWhere = struct {
	Sender       whereHelperstring
	ChannelName  whereHelperstring
	WordCount    whereHelpernull_Int64
	MessageCount whereHelpernull_Int64
	WatchTime    whereHelpernull_Int64
	CreatedAt    whereHelpernull_Time
	UpdatedAt    whereHelpernull_Time
	Emoji        whereHelpernull_String
	TextColor    whereHelpernull_String
}{
	Sender:       whereHelperstring{field: "\"user_metrics\".\"sender\""},
	ChannelName:  whereHelperstring{field: "\"user_metrics\".\"channel_name\""},
	WordCount:    whereHelpernull_Int64{field: "\"user_metrics\".\"word_count\""},
	MessageCount: whereHelpernull_Int64{field: "\"user_metrics\".\"message_count\""},
	WatchTime:    whereHelpernull_Int64{field: "\"user_metrics\".\"watch_time\""},
	CreatedAt:    whereHelpernull_Time{field: "\"user_metrics\".\"created_at\""},
	UpdatedAt:    whereHelpernull_Time{field: "\"user_metrics\".\"updated_at\""},
	Emoji:        whereHelpernull_String{field: "\"user_metrics\".\"emoji\""},
	TextColor:    whereHelpernull_String{field: "\"user_metrics\".\"text_color\""},
}

// UserMetricRels is where relationship names are stored.
var UserMetricRels = struct {
}{}

// userMetricR is where relationships are stored.
type userMetricR struct {
}

// NewStruct creates a new relationship struct
func (*userMetricR) NewStruct() *userMetricR {
	return &userMetricR{}
}

// userMetricL is where Load methods for each relationship are stored.
type userMetricL struct{}

var (
	userMetricAllColumns            = []string{"sender", "channel_name", "word_count", "message_count", "watch_time", "created_at", "updated_at", "emoji", "text_color"}
	userMetricColumnsWithoutDefault = []string{"sender", "channel_name", "word_count", "message_count", "watch_time", "created_at", "updated_at", "emoji", "text_color"}
	userMetricColumnsWithDefault    = []string{}
	userMetricPrimaryKeyColumns     = []string{"sender", "channel_name"}
)

type (
	// UserMetricSlice is an alias for a slice of pointers to UserMetric.
	// This should generally be used opposed to []UserMetric.
	UserMetricSlice []*UserMetric
	// UserMetricHook is the signature for custom UserMetric hook methods
	UserMetricHook func(context.Context, boil.ContextExecutor, *UserMetric) error

	userMetricQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userMetricType                 = reflect.TypeOf(&UserMetric{})
	userMetricMapping              = queries.MakeStructMapping(userMetricType)
	userMetricPrimaryKeyMapping, _ = queries.BindMapping(userMetricType, userMetricMapping, userMetricPrimaryKeyColumns)
	userMetricInsertCacheMut       sync.RWMutex
	userMetricInsertCache          = make(map[string]insertCache)
	userMetricUpdateCacheMut       sync.RWMutex
	userMetricUpdateCache          = make(map[string]updateCache)
	userMetricUpsertCacheMut       sync.RWMutex
	userMetricUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userMetricBeforeInsertHooks []UserMetricHook
var userMetricBeforeUpdateHooks []UserMetricHook
var userMetricBeforeDeleteHooks []UserMetricHook
var userMetricBeforeUpsertHooks []UserMetricHook

var userMetricAfterInsertHooks []UserMetricHook
var userMetricAfterSelectHooks []UserMetricHook
var userMetricAfterUpdateHooks []UserMetricHook
var userMetricAfterDeleteHooks []UserMetricHook
var userMetricAfterUpsertHooks []UserMetricHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserMetric) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetricBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserMetric) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetricBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserMetric) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetricBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserMetric) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetricBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserMetric) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetricAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserMetric) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetricAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserMetric) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetricAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserMetric) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetricAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserMetric) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userMetricAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserMetricHook registers your hook function for all future operations.
func AddUserMetricHook(hookPoint boil.HookPoint, userMetricHook UserMetricHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		userMetricBeforeInsertHooks = append(userMetricBeforeInsertHooks, userMetricHook)
	case boil.BeforeUpdateHook:
		userMetricBeforeUpdateHooks = append(userMetricBeforeUpdateHooks, userMetricHook)
	case boil.BeforeDeleteHook:
		userMetricBeforeDeleteHooks = append(userMetricBeforeDeleteHooks, userMetricHook)
	case boil.BeforeUpsertHook:
		userMetricBeforeUpsertHooks = append(userMetricBeforeUpsertHooks, userMetricHook)
	case boil.AfterInsertHook:
		userMetricAfterInsertHooks = append(userMetricAfterInsertHooks, userMetricHook)
	case boil.AfterSelectHook:
		userMetricAfterSelectHooks = append(userMetricAfterSelectHooks, userMetricHook)
	case boil.AfterUpdateHook:
		userMetricAfterUpdateHooks = append(userMetricAfterUpdateHooks, userMetricHook)
	case boil.AfterDeleteHook:
		userMetricAfterDeleteHooks = append(userMetricAfterDeleteHooks, userMetricHook)
	case boil.AfterUpsertHook:
		userMetricAfterUpsertHooks = append(userMetricAfterUpsertHooks, userMetricHook)
	}
}

// One returns a single userMetric record from the query.
func (q userMetricQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserMetric, error) {
	o := &UserMetric{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for user_metrics")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserMetric records from the query.
func (q userMetricQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserMetricSlice, error) {
	var o []*UserMetric

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to UserMetric slice")
	}

	if len(userMetricAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserMetric records in the query.
func (q userMetricQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count user_metrics rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userMetricQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if user_metrics exists")
	}

	return count > 0, nil
}

// UserMetrics retrieves all the records using an executor.
func UserMetrics(mods ...qm.QueryMod) userMetricQuery {
	mods = append(mods, qm.From("\"user_metrics\""))
	return userMetricQuery{NewQuery(mods...)}
}

// FindUserMetric retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserMetric(ctx context.Context, exec boil.ContextExecutor, sender string, channelName string, selectCols ...string) (*UserMetric, error) {
	userMetricObj := &UserMetric{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_metrics\" where \"sender\"=$1 AND \"channel_name\"=$2", sel,
	)

	q := queries.Raw(query, sender, channelName)

	err := q.Bind(ctx, exec, userMetricObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from user_metrics")
	}

	return userMetricObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserMetric) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no user_metrics provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userMetricColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userMetricInsertCacheMut.RLock()
	cache, cached := userMetricInsertCache[key]
	userMetricInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userMetricAllColumns,
			userMetricColumnsWithDefault,
			userMetricColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userMetricType, userMetricMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userMetricType, userMetricMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_metrics\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_metrics\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into user_metrics")
	}

	if !cached {
		userMetricInsertCacheMut.Lock()
		userMetricInsertCache[key] = cache
		userMetricInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserMetric.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserMetric) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userMetricUpdateCacheMut.RLock()
	cache, cached := userMetricUpdateCache[key]
	userMetricUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userMetricAllColumns,
			userMetricPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update user_metrics, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_metrics\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userMetricPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userMetricType, userMetricMapping, append(wl, userMetricPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update user_metrics row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for user_metrics")
	}

	if !cached {
		userMetricUpdateCacheMut.Lock()
		userMetricUpdateCache[key] = cache
		userMetricUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userMetricQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for user_metrics")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for user_metrics")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserMetricSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userMetricPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_metrics\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userMetricPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in userMetric slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all userMetric")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserMetric) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no user_metrics provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userMetricColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userMetricUpsertCacheMut.RLock()
	cache, cached := userMetricUpsertCache[key]
	userMetricUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			userMetricAllColumns,
			userMetricColumnsWithDefault,
			userMetricColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			userMetricAllColumns,
			userMetricPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert user_metrics, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(userMetricPrimaryKeyColumns))
			copy(conflict, userMetricPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_metrics\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(userMetricType, userMetricMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userMetricType, userMetricMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert user_metrics")
	}

	if !cached {
		userMetricUpsertCacheMut.Lock()
		userMetricUpsertCache[key] = cache
		userMetricUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserMetric record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserMetric) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no UserMetric provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userMetricPrimaryKeyMapping)
	sql := "DELETE FROM \"user_metrics\" WHERE \"sender\"=$1 AND \"channel_name\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from user_metrics")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for user_metrics")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userMetricQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no userMetricQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from user_metrics")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_metrics")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserMetricSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userMetricBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userMetricPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_metrics\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userMetricPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from userMetric slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_metrics")
	}

	if len(userMetricAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserMetric) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserMetric(ctx, exec, o.Sender, o.ChannelName)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserMetricSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserMetricSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userMetricPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_metrics\".* FROM \"user_metrics\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userMetricPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in UserMetricSlice")
	}

	*o = slice

	return nil
}

// UserMetricExists checks if the UserMetric row exists.
func UserMetricExists(ctx context.Context, exec boil.ContextExecutor, sender string, channelName string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_metrics\" where \"sender\"=$1 AND \"channel_name\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, sender, channelName)
	}
	row := exec.QueryRowContext(ctx, sql, sender, channelName)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if user_metrics exists")
	}

	return exists, nil
}
